# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('memo', models.TextField()),
                ('publication_date', models.DateTimeField()),
            ],
        ),
    ]
