# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='publication_date',
        ),
    ]
